name:           mismatchtea
url:            http://mismatchtea.uk
description:    "resources and ideas for teaching maths"
permalink:      /blog/:year/:title
exclude:        [mmt.sublime-project,mmt.sublime-workspacel]
postAssets:      /items #location of images and resources for posts
resourceAssets:  /presentations/items #location of presentations
sass:
    style: :compressed

collections:
  presentations:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: presentations
    values:
      layout: presentation